# Generated by Django 4.0.5 on 2022-12-27 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registration', '0004_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='status',
            field=models.CharField(default='MPS', max_length=3),
        ),
    ]
