# Generated by Django 4.0.5 on 2022-12-27 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registration', '0006_remove_student_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='status',
            field=models.CharField(default='MP', max_length=3),
        ),
    ]
