# Generated by Django 4.0.5 on 2022-12-27 03:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Registration', '0008_remove_student_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='phone',
            new_name='phone_no',
        ),
    ]
