# Generated by Django 4.0.5 on 2022-12-27 03:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Registration', '0009_rename_phone_student_phone_no'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
    ]
