# Generated by Django 4.0.5 on 2022-12-27 03:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Registration', '0011_student'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='phone_no',
            new_name='phone',
        ),
    ]
