# Generated by Django 4.0.5 on 2023-02-08 02:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Registration', '0013_student_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='status',
        ),
    ]
